countries = []
countries.append("Norway")
countries.append("Sweden")
countries.insert(1, "Denmark")
countries.insert(0, "Iceland")
print(countries)
countries.remove("Denmark")
print(countries)
del countries[0]
print(countries)
countries.append("USA")
countries.append("Canada")
print(countries)
countries.pop(2)
print(countries)
popped = countries.pop()
print(popped)
print(countries)
countries.append("Finland")
print(countries)
print(sorted(countries))
print(sorted(countries, reverse=True))
countries.sort()
print(countries)
countries.sort(reverse=True)
print(countries)
print(f"We now have {len(countries)} countries to show")
