guests = ["buddha", "socrates", "oppenheimer"]
print(f"{guests[1].title()} couldn't make it.")
guests[1] = "plato"
print(f"Hello {guests[0].title()}, you're welcome to dinner.")
print(f"Hello {guests[1].title()}, you're welcome to dinner.")
print(f"Hello {guests[2].title()}, you're welcome to dinner.")
print("We found a bigger table.")
guests.insert(0, "shakespeare")
guests.insert(1, "bacon")
guests.append("gustav vasa")
print(f"Hello {guests[0].title()}, you're welcome to dinner.")
print(f"Hello {guests[1].title()}, you're welcome to dinner.")
print(f"Hello {guests[2].title()}, you're welcome to dinner.")
print(f"Hello {guests[3].title()}, you're welcome to dinner.")
print(f"Hello {guests[4].title()}, you're welcome to dinner.")
print(f"Hello {guests[5].title()}, you're welcome to dinner.")
print("Sorry, only two people can be invited.")
popped = guests.pop()
print(f"I am sorry but {popped.title()} is disinvited.")
popped = guests.pop(0)
print(f"I am sorry but {popped.title()} is disinvited.")
popped = guests.pop(2)
print(f"I am sorry but {popped.title()} is disinvited.")
popped = guests.pop()
print(f"I am sorry but {popped.title()} is disinvited.")
print(f"Dear {guests[0].title()}, you are still welcome.")
print(f"Dear {guests[1].title()}, you are still welcome.")
print(guests)
del guests[1]
print(guests)
del guests[0]
print(guests)
