visit = ["svalbard", "iceland", "texas", "alabama", "tokyo", "japan"]
print(visit)
print(sorted(visit))
print(visit)
print(sorted(visit, reverse=True))
print(visit)
visit.reverse()
print(visit)
visit.reverse()
print(visit)
visit.sort()
print(visit)
visit.sort(reverse=True)
print(visit)